using System;
using System.Collections.Generic;
using Godot;
using HarmonyLib;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Cards;
using MegaCrit.Sts2.Core.Nodes.Cards;
using Void = MegaCrit.Sts2.Core.Models.Cards.Void;

namespace AnimeWaifuSilent.AnimeWaifuSilentCode;

/// <summary>
/// 拦截 <see cref="CardModel.Portrait"/> 的读取过程，将指定卡牌的原始立绘替换为模组内的二次元卡图。
/// 这里还会优先生成并缓存带有 Mipmap 的纹理，为预览卡片时的平滑显示提供更合适的资源数据，
/// 从而配合 <c>CardFilterUtility.cs</c> 一起减轻卡牌在缩放或放大预览时出现的边缘锯齿。
/// </summary>
[HarmonyPatch(typeof(CardModel), nameof(CardModel.Portrait), MethodType.Getter)]
public static class CardPortraitReplacementPatch
{
    private const string ModPortraitRoot = "res://AnimeWaifuSilent/card_portraits/";

    // 该字典内容可由工作流根据 `AnimeWaifuSilent/card_portraits` 目录自动刷新。
    private static readonly Dictionary<Type, string> Replacements = new()
    {
        // <auto-generated-replacements>
        // Silent 卡池
        { typeof(Accelerant), "res://AnimeWaifuSilent/card_portraits/silent/accelerant.png" },
        { typeof(Accuracy), "res://AnimeWaifuSilent/card_portraits/silent/accuracy.png" },
        { typeof(Acrobatics), "res://AnimeWaifuSilent/card_portraits/silent/acrobatics.png" },
        { typeof(Adrenaline), "res://AnimeWaifuSilent/card_portraits/silent/adrenaline.png" },
        { typeof(Afterimage), "res://AnimeWaifuSilent/card_portraits/silent/afterimage.png" },
        { typeof(BladeDance), "res://AnimeWaifuSilent/card_portraits/silent/blade_dance.png" },
        { typeof(Blur), "res://AnimeWaifuSilent/card_portraits/silent/blur.png" },
        { typeof(BulletTime), "res://AnimeWaifuSilent/card_portraits/silent/bullet_time.png" },
        { typeof(CalculatedGamble), "res://AnimeWaifuSilent/card_portraits/silent/calculated_gamble.png" },
        { typeof(DaggerThrow), "res://AnimeWaifuSilent/card_portraits/silent/dagger_throw.png" },
        { typeof(Dash), "res://AnimeWaifuSilent/card_portraits/silent/dash.png" },
        { typeof(DefendSilent), "res://AnimeWaifuSilent/card_portraits/silent/defend_silent.png" },
        { typeof(Distraction), "res://AnimeWaifuSilent/card_portraits/silent/distraction.png" },
        { typeof(Envenom), "res://AnimeWaifuSilent/card_portraits/silent/envenom.png" },
        { typeof(Expertise), "res://AnimeWaifuSilent/card_portraits/silent/expertise.png" },
        { typeof(Expose), "res://AnimeWaifuSilent/card_portraits/silent/expose.png" },
        { typeof(FanOfKnives), "res://AnimeWaifuSilent/card_portraits/silent/fan_of_knives.png" },
        { typeof(Finisher), "res://AnimeWaifuSilent/card_portraits/silent/finisher.png" },
        { typeof(FlickFlack), "res://AnimeWaifuSilent/card_portraits/silent/flick_flack.png" },
        { typeof(Footwork), "res://AnimeWaifuSilent/card_portraits/silent/footwork.png" },
        { typeof(GrandFinale), "res://AnimeWaifuSilent/card_portraits/silent/grand_finale.png" },
        { typeof(InfiniteBlades), "res://AnimeWaifuSilent/card_portraits/silent/infinite_blades.png" },
        { typeof(Malaise), "res://AnimeWaifuSilent/card_portraits/silent/malaise.png" },
        { typeof(MementoMori), "res://AnimeWaifuSilent/card_portraits/silent/memento_mori.png" },
        { typeof(Murder), "res://AnimeWaifuSilent/card_portraits/silent/murder.png" },
        { typeof(Neutralize), "res://AnimeWaifuSilent/card_portraits/silent/neutralize.png" },
        { typeof(Nightmare), "res://AnimeWaifuSilent/card_portraits/silent/nightmare.png" },
        { typeof(NoxiousFumes), "res://AnimeWaifuSilent/card_portraits/silent/noxious_fumes.png" },
        { typeof(Outmaneuver), "res://AnimeWaifuSilent/card_portraits/silent/outmaneuver.png" },
        { typeof(PiercingWail), "res://AnimeWaifuSilent/card_portraits/silent/piercing_wail.png" },
        { typeof(Prepared), "res://AnimeWaifuSilent/card_portraits/silent/prepared.png" },
        { typeof(Reflex), "res://AnimeWaifuSilent/card_portraits/silent/reflex.png" },
        { typeof(Skewer), "res://AnimeWaifuSilent/card_portraits/silent/skewer.png" },
        { typeof(Slice), "res://AnimeWaifuSilent/card_portraits/silent/slice.png" },
        { typeof(Strangle), "res://AnimeWaifuSilent/card_portraits/silent/strangle.png" },
        { typeof(StrikeSilent), "res://AnimeWaifuSilent/card_portraits/silent/strike_silent.png" },
        { typeof(Survivor), "res://AnimeWaifuSilent/card_portraits/silent/survivor.png" },
        { typeof(Tactician), "res://AnimeWaifuSilent/card_portraits/silent/tactician.png" },
        { typeof(TheHunt), "res://AnimeWaifuSilent/card_portraits/silent/the_hunt.png" },
        { typeof(WellLaidPlans), "res://AnimeWaifuSilent/card_portraits/silent/well_laid_plans.png" },

        // Colorless 卡池
        { typeof(Alchemize), "res://AnimeWaifuSilent/card_portraits/colorless/alchemize.png" },
        { typeof(Panache), "res://AnimeWaifuSilent/card_portraits/colorless/panache.png" },

        // Event 卡池
        { typeof(Apparition), "res://AnimeWaifuSilent/card_portraits/event/apparition.png" },
        { typeof(WraithForm), "res://AnimeWaifuSilent/card_portraits/event/wraith_form.png" },

        // Curse 卡池
        { typeof(AscendersBane), "res://AnimeWaifuSilent/card_portraits/curse/ascenders_bane.png" },

        // Necrobinder 卡池
        { typeof(Fear), "res://AnimeWaifuSilent/card_portraits/necrobinder/fear.png" },

        // Status 卡池
        { typeof(Infection), "res://AnimeWaifuSilent/card_portraits/status/infection.png" },
        { typeof(Void), "res://AnimeWaifuSilent/card_portraits/status/void.png" },

        // Token 卡池
        { typeof(Shiv), "res://AnimeWaifuSilent/card_portraits/token/shiv.png" },

        // </auto-generated-replacements>
    };

    // 缓存已经生成过 Mipmap 的替换贴图，避免每次读取卡图时重复解码和重复生成。
    private static readonly Dictionary<string, Texture2D> ReplacementTextureCache = new(StringComparer.OrdinalIgnoreCase);

    // 记录本模组运行时创建出的贴图实例，供过滤补丁快速判断当前纹理是否来自本模组。
    private static readonly HashSet<ulong> ReplacementTextureIds = new();

    /// <summary>
    /// 在游戏请求卡牌立绘时，将其替换为本模组对应的图片资源。
    /// </summary>
    static void Postfix(CardModel __instance, ref Texture2D __result)
    {
        if (!TryGetReplacementPath(__instance, out string path))
            return;

        Texture2D? portrait = LoadReplacementTexture(path);
        if (portrait != null)
            __result = portrait;
    }

    /// <summary>
    /// 判断某张纹理是否属于本模组的替换卡图。
    /// </summary>
    public static bool IsModPortraitTexture(Texture2D? texture)
    {
        if (texture == null)
        {
            return false;
        }

        if (ReplacementTextureIds.Contains(texture.GetInstanceId()))
        {
            return true;
        }

        string resourcePath = texture.ResourcePath ?? string.Empty;
        return resourcePath.StartsWith(ModPortraitRoot, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// 判断某张卡牌当前使用的立绘是否来自本模组。
    /// </summary>
    public static bool IsModPortraitModel(CardModel? model)
    {
        return IsModPortraitTexture(model?.Portrait);
    }

    /// <summary>
    /// 加载并缓存替换立绘。
    /// 会尽量优先创建带 Mipmap 的纹理，以便在卡牌缩放和放大预览时减少锯齿。
    /// </summary>
    private static Texture2D? LoadReplacementTexture(string path)
    {
        if (ReplacementTextureCache.TryGetValue(path, out var cached))
        {
            return cached;
        }

        if (!ResourceLoader.Exists(path))
        {
            return null;
        }

        Texture2D? textureWithMipmaps = CreateMipmappedTextureFromFile(path);
        if (textureWithMipmaps == null)
        {
            Texture2D sourceTexture = ResourceLoader.Load<Texture2D>(path, null, ResourceLoader.CacheMode.Reuse);
            if (sourceTexture == null)
            {
                return null;
            }

            textureWithMipmaps = CreateMipmappedTexture(sourceTexture) ?? sourceTexture;
        }

        ReplacementTextureCache[path] = textureWithMipmaps;
        ReplacementTextureIds.Add(textureWithMipmaps.GetInstanceId());
        return textureWithMipmaps;
    }

    /// <summary>
    /// 根据卡牌运行时类型查找对应的替换图片路径。
    /// </summary>
    private static bool TryGetReplacementPath(CardModel model, out string path)
    {
        if (Replacements.TryGetValue(model.GetType(), out string? value) && !string.IsNullOrEmpty(value))
        {
            path = value;
            return true;
        }

        path = string.Empty;
        return false;
    }

    /// <summary>
    /// 直接从文件读取图片并生成带 Mipmap 的纹理。
    /// 这样在卡牌被缩小或放大时，预览边缘会更平滑。
    /// </summary>
    private static Texture2D? CreateMipmappedTextureFromFile(string path)
    {
        Image image = new();
        string absolutePath = ProjectSettings.GlobalizePath(path);
        Error loadError = image.Load(absolutePath);
        if (loadError != Error.Ok)
        {
            loadError = image.Load(path);
            if (loadError != Error.Ok)
            {
                return null;
            }
        }

        if (!image.HasMipmaps())
        {
            image.GenerateMipmaps();
        }

        return ImageTexture.CreateFromImage(image);
    }

    /// <summary>
    /// 从已有纹理对象中取出图像数据，并补生成 Mipmap 后重新创建纹理。
    /// </summary>
    private static Texture2D? CreateMipmappedTexture(Texture2D sourceTexture)
    {
        Image image = sourceTexture.GetImage();
        if (image == null || image.IsEmpty())
        {
            return null;
        }

        if (!image.HasMipmaps())
        {
            image.GenerateMipmaps();
        }

        return ImageTexture.CreateFromImage(image);
    }
}

