Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$portraitsRoot = Join-Path $repoRoot 'AnimeWaifuSilent/card_portraits'
$sourceFile = Join-Path $repoRoot 'AnimeWaifuSilentCode/CardportraitsReplacement.cs'

if (-not (Test-Path $portraitsRoot)) {
    throw "Portrait root not found: $portraitsRoot"
}

if (-not (Test-Path $sourceFile)) {
    throw "Source file not found: $sourceFile"
}

$typeAliases = @{
    'defend_silent' = 'DefendSilent'
    'strike_silent' = 'StrikeSilent'
}

$poolOrder = @('silent', 'colorless', 'event', 'curse', 'necrobinder', 'status', 'token')
$poolLabels = @{
    'silent' = 'Silent 卡池'
    'colorless' = 'Colorless 卡池'
    'event' = 'Event 卡池'
    'curse' = 'Curse 卡池'
    'necrobinder' = 'Necrobinder 卡池'
    'status' = 'Status 卡池'
    'token' = 'Token 卡池'
}

function Convert-ToTypeName([string]$stem) {
    if ($typeAliases.ContainsKey($stem)) {
        return $typeAliases[$stem]
    }

    if ($stem -notmatch '^[A-Za-z]') {
        return $null
    }

    $parts = $stem -split '[_\-\s]+' | Where-Object { $_ }
    if (-not $parts) {
        return $null
    }

    return (($parts | ForEach-Object {
        if ($_.Length -eq 1) {
            $_.ToUpperInvariant()
        }
        else {
            $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1)
        }
    }) -join '')
}

$pngFiles = Get-ChildItem -Path $portraitsRoot -Recurse -File |
    Where-Object { $_.Extension.Equals('.png', [System.StringComparison]::OrdinalIgnoreCase) }

if (-not $pngFiles) {
    throw "No portrait .png files found under $portraitsRoot"
}

$seenTypes = @{}
$generatedLines = New-Object 'System.Collections.Generic.List[string]'
$generatedLines.Add('        // <auto-generated-replacements>')

foreach ($pool in $poolOrder) {
    $poolFiles = $pngFiles | Where-Object {
        $relative = [System.IO.Path]::GetRelativePath($portraitsRoot, $_.FullName).Replace('\', '/')
        $relative.StartsWith("$pool/", [System.StringComparison]::OrdinalIgnoreCase)
    } | Sort-Object Name

    if (-not $poolFiles) {
        continue
    }

    $label = if ($poolLabels.ContainsKey($pool)) { $poolLabels[$pool] } else { $pool }
    $generatedLines.Add("        // $label")

    foreach ($file in $poolFiles) {
        $stem = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        $typeName = Convert-ToTypeName $stem

        if ([string]::IsNullOrWhiteSpace($typeName)) {
            Write-Warning "Skipping unsupported portrait file name: $($file.Name)"
            continue
        }

        if ($seenTypes.ContainsKey($typeName)) {
            Write-Warning "Skipping duplicate type mapping for $typeName from $($file.FullName)"
            continue
        }

        $seenTypes[$typeName] = $true

        $relativeFromRepo = [System.IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
        $resourcePath = "res://$relativeFromRepo"
        $generatedLines.Add("        { typeof($typeName), `"$resourcePath`" },")
    }

    $generatedLines.Add('')
}

$generatedLines.Add('        // </auto-generated-replacements>')

$content = Get-Content $sourceFile -Raw
$startMarker = '        // <auto-generated-replacements>'
$endMarker = '        // </auto-generated-replacements>'

$startIndex = $content.IndexOf($startMarker, [System.StringComparison]::Ordinal)
$endIndex = $content.IndexOf($endMarker, [System.StringComparison]::Ordinal)

if ($startIndex -lt 0 -or $endIndex -lt 0 -or $endIndex -lt $startIndex) {
    throw "Auto-generated replacement markers were not found in $sourceFile"
}

$endIndex += $endMarker.Length
$newBlock = $generatedLines -join [Environment]::NewLine
$newContent = $content.Substring(0, $startIndex) + $newBlock + $content.Substring($endIndex)

if ($newContent -ne $content) {
    [System.IO.File]::WriteAllText($sourceFile, $newContent, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Updated portrait dictionary in $sourceFile"
}
else {
    Write-Host 'Portrait dictionary is already up to date.'
}
